# Generated by Django 5.2.7 on 2025-10-26 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du type')),
                ('code', models.CharField(choices=[('technique', 'Problème technique'), ('contenu', 'Problème de contenu'), ('acces', "Problème d'accès"), ('evaluation', "Problème d'évaluation"), ('forum', 'Problème de forum'), ('autre', 'Autre')], max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='bi-exclamation-triangle', help_text="Classe d'icône Bootstrap", max_length=50)),
                ('color', models.CharField(default='#ffc107', help_text='Couleur hexadécimale', max_length=7)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de réclamation',
                'verbose_name_plural': 'Types de réclamations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la réclamation')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours de traitement'), ('en_attente', 'En attente de réponse'), ('resolue', 'Résolue'), ('fermee', 'Fermée'), ('rejetee', 'Rejetée')], default='ouverte', max_length=20, verbose_name='Statut')),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='reclamations/fichiers/%Y/%m/', verbose_name='Fichier joint')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('url_probleme', models.URLField(blank=True, verbose_name='URL du problème')),
                ('navigateur', models.CharField(blank=True, max_length=100, verbose_name='Navigateur')),
                ('systeme_exploitation', models.CharField(blank=True, max_length=100, verbose_name="Système d'exploitation")),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('type_reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclamations.typereclamation', verbose_name='Type de réclamation')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu du commentaire')),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='reclamations/commentaires/%Y/%m/', verbose_name='Fichier joint')),
                ('is_internal', models.BooleanField(default=False, verbose_name="Commentaire interne (non visible par l'utilisateur)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='reclamations.reclamation')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuiviReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=20, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(max_length=20, verbose_name='Nouveau statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire sur le changement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du changement')),
                ('modifie_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='reclamations.reclamation')),
            ],
            options={
                'verbose_name': 'Suivi de réclamation',
                'verbose_name_plural': 'Suivis de réclamations',
                'ordering': ['-created_at'],
            },
        ),
    ]
