# Generated by Django 5.2.7 on 2025-10-26 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReponseAdministrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la réponse')),
                ('contenu', models.TextField(verbose_name='Contenu de la réponse')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publiee', 'Publiée'), ('archivee', 'Archivée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='reclamations/reponses_admin/%Y/%m/', verbose_name='Fichier joint')),
                ('notifier_utilisateur', models.BooleanField(default=True, verbose_name="Notifier l'utilisateur par email")),
                ('email_envoye', models.BooleanField(default=False, verbose_name='Email envoyé')),
                ('date_envoi_email', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi de l'email")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('lu_par_utilisateur', models.BooleanField(default=False, verbose_name="Lu par l'utilisateur")),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('administrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_admin', to='reclamations.reclamation')),
            ],
            options={
                'verbose_name': 'Réponse administrateur',
                'verbose_name_plural': 'Réponses administrateur',
                'ordering': ['-created_at'],
            },
        ),
    ]
