# Generated by Django 5.2.7 on 2025-10-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='popularity_refreshed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Score actualisé le'),
        ),
        migrations.AddField(
            model_name='topic',
            name='popularity_score',
            field=models.FloatField(default=0.0, verbose_name='Score de popularité'),
        ),
    ]
