# Generated by Django 5.2.7 on 2025-10-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topic_popularity_refreshed_at_topic_popularity_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='popularity_refreshed_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='popularity_score',
        ),
    ]
