# Generated by Django 4.2 on 2025-10-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodule',
            name='content',
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/modules/', verbose_name='Fichier du module'),
        ),
    ]
