# Generated by Django 5.1.5 on 2025-10-24 01:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "icon",
                    models.CharField(
                        default="bi-star",
                        help_text="Classe d'icône Bootstrap",
                        max_length=50,
                    ),
                ),
                (
                    "points_reward",
                    models.IntegerField(default=0, verbose_name="Points de récompense"),
                ),
                (
                    "experience_reward",
                    models.IntegerField(
                        default=0, verbose_name="Expérience de récompense"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Réalisation",
                "verbose_name_plural": "Réalisations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("achievement", "Réussite"),
                            ("streak", "Série"),
                            ("speed", "Rapidité"),
                            ("accuracy", "Précision"),
                            ("participation", "Participation"),
                            ("mastery", "Maîtrise"),
                            ("special", "Spécial"),
                        ],
                        max_length=20,
                        verbose_name="Type de badge",
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Commun"),
                            ("uncommon", "Peu commun"),
                            ("rare", "Rare"),
                            ("epic", "Épique"),
                            ("legendary", "Légendaire"),
                        ],
                        default="common",
                        max_length=15,
                        verbose_name="Rareté",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-trophy",
                        help_text="Classe d'icône Bootstrap",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#ffc107",
                        help_text="Couleur hexadécimale",
                        max_length=7,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="badges/",
                        verbose_name="Image du badge",
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(max_length=50, verbose_name="Type de condition"),
                ),
                (
                    "condition_value",
                    models.IntegerField(verbose_name="Valeur de condition"),
                ),
                (
                    "condition_description",
                    models.TextField(verbose_name="Description de la condition"),
                ),
                (
                    "points_reward",
                    models.IntegerField(default=0, verbose_name="Points de récompense"),
                ),
                (
                    "experience_reward",
                    models.IntegerField(
                        default=0, verbose_name="Expérience de récompense"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "ordering": ["rarity", "name"],
            },
        ),
        migrations.CreateModel(
            name="DifficultyLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nom")),
                ("level", models.IntegerField(unique=True, verbose_name="Niveau")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#28a745",
                        help_text="Couleur hexadécimale",
                        max_length=7,
                    ),
                ),
                (
                    "points_multiplier",
                    models.FloatField(
                        default=1.0, verbose_name="Multiplicateur de points"
                    ),
                ),
            ],
            options={
                "verbose_name": "Niveau de difficulté",
                "verbose_name_plural": "Niveaux de difficulté",
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la matière"),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-book",
                        help_text="Classe d'icône Bootstrap",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="Couleur hexadécimale",
                        max_length=7,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Matière",
                "verbose_name_plural": "Matières",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="Instructions"),
                ),
                (
                    "time_limit",
                    models.IntegerField(
                        default=30, verbose_name="Durée limite (minutes)"
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(
                        default=3, verbose_name="Nombre maximum de tentatives"
                    ),
                ),
                (
                    "passing_score",
                    models.IntegerField(
                        default=70, verbose_name="Score de réussite (%)"
                    ),
                ),
                (
                    "points_available",
                    models.IntegerField(default=100, verbose_name="Points disponibles"),
                ),
                (
                    "experience_points",
                    models.IntegerField(default=50, verbose_name="Points d'expérience"),
                ),
                (
                    "is_ai_generated",
                    models.BooleanField(default=True, verbose_name="Généré par IA"),
                ),
                (
                    "ai_prompt",
                    models.TextField(blank=True, verbose_name="Prompt IA utilisé"),
                ),
                (
                    "ai_model_version",
                    models.CharField(
                        default="1.0",
                        max_length=50,
                        verbose_name="Version du modèle IA",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publié"),
                            ("archived", "Archivé"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "total_attempts",
                    models.IntegerField(default=0, verbose_name="Total des tentatives"),
                ),
                (
                    "average_score",
                    models.FloatField(default=0.0, verbose_name="Score moyen"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_quizzes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "difficulty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="gamification.difficultylevel",
                        verbose_name="Difficulté",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="gamification.subject",
                        verbose_name="Matière",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quiz",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(verbose_name="Texte de la question"),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Choix multiple"),
                            ("true_false", "Vrai/Faux"),
                            ("fill_blank", "Texte à trous"),
                            ("essay", "Question ouverte"),
                        ],
                        default="multiple_choice",
                        max_length=20,
                        verbose_name="Type de question",
                    ),
                ),
                (
                    "option_a",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Option A"
                    ),
                ),
                (
                    "option_b",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Option B"
                    ),
                ),
                (
                    "option_c",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Option C"
                    ),
                ),
                (
                    "option_d",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Option D"
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(max_length=500, verbose_name="Réponse correcte"),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, verbose_name="Explication"),
                ),
                ("points", models.IntegerField(default=10, verbose_name="Points")),
                (
                    "difficulty_score",
                    models.FloatField(
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Score de difficulté",
                    ),
                ),
                (
                    "is_ai_generated",
                    models.BooleanField(default=True, verbose_name="Généré par IA"),
                ),
                (
                    "ai_confidence",
                    models.FloatField(default=0.8, verbose_name="Confiance IA"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Ordre")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="gamification.quiz",
                        verbose_name="Quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "leaderboard_type",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("subject", "Par matière"),
                            ("weekly", "Hebdomadaire"),
                            ("monthly", "Mensuel"),
                            ("level", "Par niveau"),
                        ],
                        max_length=15,
                        verbose_name="Type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamification.subject",
                        verbose_name="Matière",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classement",
                "verbose_name_plural": "Classements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_points",
                    models.IntegerField(default=0, verbose_name="Points totaux"),
                ),
                (
                    "experience_points",
                    models.IntegerField(default=0, verbose_name="Points d'expérience"),
                ),
                ("level", models.IntegerField(default=1, verbose_name="Niveau")),
                (
                    "quizzes_completed",
                    models.IntegerField(default=0, verbose_name="Quiz complétés"),
                ),
                (
                    "quizzes_passed",
                    models.IntegerField(default=0, verbose_name="Quiz réussis"),
                ),
                (
                    "total_attempts",
                    models.IntegerField(default=0, verbose_name="Total des tentatives"),
                ),
                (
                    "average_score",
                    models.FloatField(default=0.0, verbose_name="Score moyen"),
                ),
                (
                    "current_streak",
                    models.IntegerField(default=0, verbose_name="Série actuelle"),
                ),
                (
                    "longest_streak",
                    models.IntegerField(default=0, verbose_name="Plus longue série"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière activité"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "favorite_subjects",
                    models.ManyToManyField(
                        blank=True,
                        to="gamification.subject",
                        verbose_name="Matières préférées",
                    ),
                ),
                (
                    "preferred_difficulty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gamification.difficultylevel",
                        verbose_name="Difficulté préférée",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gamification_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil de gamification",
                "verbose_name_plural": "Profils de gamification",
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0, verbose_name="Score")),
                (
                    "percentage",
                    models.FloatField(default=0.0, verbose_name="Pourcentage"),
                ),
                (
                    "points_earned",
                    models.IntegerField(default=0, verbose_name="Points obtenus"),
                ),
                (
                    "experience_earned",
                    models.IntegerField(default=0, verbose_name="Expérience obtenue"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Commencé à"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminé à"
                    ),
                ),
                (
                    "time_taken",
                    models.IntegerField(
                        default=0, verbose_name="Temps pris (secondes)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "En cours"),
                            ("completed", "Terminé"),
                            ("abandoned", "Abandonné"),
                            ("timeout", "Temps écoulé"),
                        ],
                        default="in_progress",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "attempt_number",
                    models.IntegerField(default=1, verbose_name="Numéro de tentative"),
                ),
                ("answers", models.JSONField(default=dict, verbose_name="Réponses")),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="gamification.quiz",
                        verbose_name="Quiz",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Étudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentative de quiz",
                "verbose_name_plural": "Tentatives de quiz",
                "ordering": ["-started_at"],
                "unique_together": {("student", "quiz", "attempt_number")},
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Obtenu le"),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="gamification.achievement",
                        verbose_name="Réalisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réalisation utilisateur",
                "verbose_name_plural": "Réalisations utilisateurs",
                "ordering": ["-earned_at"],
                "unique_together": {("user", "achievement")},
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Obtenu le"),
                ),
                (
                    "context",
                    models.JSONField(default=dict, verbose_name="Contexte d'obtention"),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="gamification.badge",
                        verbose_name="Badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge utilisateur",
                "verbose_name_plural": "Badges utilisateurs",
                "ordering": ["-earned_at"],
                "unique_together": {("user", "badge")},
            },
        ),
    ]
