# Generated by Django 5.2.7 on 2025-10-25 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la room')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('room_code', models.CharField(max_length=8, unique=True, verbose_name='Code de la room')),
                ('max_participants', models.IntegerField(default=50, verbose_name='Nombre maximum de participants')),
                ('time_limit_override', models.IntegerField(blank=True, help_text='Laissez vide pour utiliser la durée du quiz', null=True, verbose_name='Durée limite personnalisée (minutes)')),
                ('scheduled_start', models.DateTimeField(blank=True, null=True, verbose_name='Début programmé')),
                ('scheduled_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin programmée')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Début réel')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin réelle')),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('active', 'Active'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='waiting', max_length=15, verbose_name='Statut')),
                ('show_results_immediately', models.BooleanField(default=True, verbose_name='Afficher les résultats immédiatement')),
                ('allow_review', models.BooleanField(default=True, verbose_name='Permettre la révision des réponses')),
                ('show_leaderboard', models.BooleanField(default=True, verbose_name='Afficher le classement')),
                ('enable_badges', models.BooleanField(default=True, verbose_name='Activer les badges')),
                ('total_participants', models.IntegerField(default=0, verbose_name='Total des participants')),
                ('completed_participants', models.IntegerField(default=0, verbose_name='Participants ayant terminé')),
                ('average_score', models.FloatField(default=0.0, verbose_name='Score moyen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='gamification.quiz', verbose_name='Quiz')),
                ('teacher', models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Room de quiz',
                'verbose_name_plural': 'Rooms de quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('joined', 'Rejoint'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('abandoned', 'Abandonné')], default='joined', max_length=15, verbose_name='Statut')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Rejoint le')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Commencé le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('quiz_attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_participant', to='gamification.quizattempt', verbose_name='Tentative de quiz')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gamification.quizroom', verbose_name='Room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_participations', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Participant de room',
                'verbose_name_plural': 'Participants de room',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='Score')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Pourcentage')),
                ('grade', models.CharField(blank=True, max_length=2, verbose_name='Grade')),
                ('rank', models.IntegerField(default=0, verbose_name='Classement')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Réponses correctes')),
                ('wrong_answers', models.IntegerField(default=0, verbose_name='Réponses incorrectes')),
                ('skipped_answers', models.IntegerField(default=0, verbose_name='Réponses sautées')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Total de questions')),
                ('time_taken', models.IntegerField(default=0, verbose_name='Temps pris (secondes)')),
                ('average_time_per_question', models.FloatField(default=0.0, verbose_name='Temps moyen par question')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Points gagnés')),
                ('experience_earned', models.IntegerField(default=0, verbose_name='Expérience gagnée')),
                ('easy_correct', models.IntegerField(default=0, verbose_name='Faciles correctes')),
                ('medium_correct', models.IntegerField(default=0, verbose_name='Moyennes correctes')),
                ('hard_correct', models.IntegerField(default=0, verbose_name='Difficiles correctes')),
                ('strengths', models.JSONField(default=list, verbose_name='Points forts')),
                ('weaknesses', models.JSONField(default=list, verbose_name='Points faibles')),
                ('recommendations', models.JSONField(default=list, verbose_name='Recommandations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('badges_earned', models.ManyToManyField(blank=True, to='gamification.badge', verbose_name='Badges gagnés')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='gamification.roomparticipant', verbose_name='Participant')),
            ],
            options={
                'verbose_name': 'Résultat de room',
                'verbose_name_plural': 'Résultats de room',
                'ordering': ['-percentage', '-score'],
            },
        ),
        migrations.AddIndex(
            model_name='quizroom',
            index=models.Index(fields=['room_code'], name='gamificatio_room_co_4ec227_idx'),
        ),
        migrations.AddIndex(
            model_name='quizroom',
            index=models.Index(fields=['status'], name='gamificatio_status_2cebf5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomparticipant',
            unique_together={('room', 'student')},
        ),
    ]
